// src/succession-automation/src/domain/events/probate-application.events.ts
import {
  ApplicationStatus,
  FilingPriority,
  ProbateApplicationType,
} from '../aggregates/probate-application.aggregate';
import { DomainEvent } from '../base/domain-event';

// ==================== APPLICATION LIFECYCLE EVENTS ====================

/**
 * Event: Probate Application Created
 */
export class ProbateApplicationCreated extends DomainEvent<{
  applicationId: string;
  estateId: string;
  readinessAssessmentId: string;
  applicationType: ProbateApplicationType;
  targetCourt: string;
  courtStation: string;
  createdAt: Date;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      estateId: string;
      readinessAssessmentId: string;
      applicationType: ProbateApplicationType;
      targetCourt: string;
      courtStation: string;
      createdAt: Date;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

/**
 * Event: Application Auto-Generated
 */
export class ApplicationAutoGenerated extends DomainEvent<{
  applicationId: string;
  estateId: string;
  readinessScore: number;
  applicationType: ProbateApplicationType;
  autoGeneratedAt: Date;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      estateId: string;
      readinessScore: number;
      applicationType: ProbateApplicationType;
      autoGeneratedAt: Date;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

/**
 * Event: Application Ready to File
 */
export class ApplicationReadyToFile extends DomainEvent<{
  applicationId: string;
  estateId: string;
  canFile: boolean;
  checkedAt: Date;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      estateId: string;
      canFile: boolean;
      checkedAt: Date;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

/**
 * Event: Application Filed
 */
export class ApplicationFiled extends DomainEvent<{
  applicationId: string;
  estateId: string;
  courtCaseNumber: string;
  courtStation: string;
  filingMethod: 'E_FILING' | 'PHYSICAL' | 'COURT_REGISTRY';
  filedAt: Date;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      estateId: string;
      courtCaseNumber: string;
      courtStation: string;
      filingMethod: 'E_FILING' | 'PHYSICAL' | 'COURT_REGISTRY';
      filedAt: Date;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

/**
 * Event: Application Withdrawn
 */
export class ApplicationWithdrawn extends DomainEvent<{
  applicationId: string;
  estateId: string;
  reason: string;
  withdrawnAt: Date;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      estateId: string;
      reason: string;
      withdrawnAt: Date;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

// ==================== FORM MANAGEMENT EVENTS ====================

/**
 * Event: Form Generated
 */
export class FormGenerated extends DomainEvent<{
  applicationId: string;
  estateId: string;
  formId: string;
  formType: string;
  formCode: string;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      estateId: string;
      formId: string;
      formType: string;
      formCode: string;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

/**
 * Event: Forms Regenerated
 */
export class FormsRegenerated extends DomainEvent<{
  applicationId: string;
  estateId: string;
  totalForms: number;
  reason: string;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      estateId: string;
      totalForms: number;
      reason: string;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

/**
 * Event: Forms Reviewed
 */
export class FormsReviewed extends DomainEvent<{
  applicationId: string;
  estateId: string;
  reviewedBy: string;
  totalForms: number;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      estateId: string;
      reviewedBy: string;
      totalForms: number;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

/**
 * Event: All Forms Generated
 */
export class AllFormsGenerated extends DomainEvent<{
  applicationId: string;
  estateId: string;
  totalForms: number;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      estateId: string;
      totalForms: number;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

// ==================== CONSENT MANAGEMENT EVENTS ====================

/**
 * Event: Consent Requested
 */
export class ConsentRequested extends DomainEvent<{
  applicationId: string;
  consentId: string;
  familyMemberId: string;
  familyMemberName: string;
  method: 'SMS' | 'EMAIL' | 'BOTH';
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      consentId: string;
      familyMemberId: string;
      familyMemberName: string;
      method: 'SMS' | 'EMAIL' | 'BOTH';
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

/**
 * Event: Consent Granted
 */
export class ConsentGranted extends DomainEvent<{
  applicationId: string;
  consentId: string;
  familyMemberId: string;
  familyMemberName: string;
  method: string;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      consentId: string;
      familyMemberId: string;
      familyMemberName: string;
      method: string;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

/**
 * Event: Consent Declined
 */
export class ConsentDeclined extends DomainEvent<{
  applicationId: string;
  consentId: string;
  familyMemberId: string;
  familyMemberName: string;
  reason: string;
  category: 'DISPUTE' | 'NOT_INFORMED' | 'DISAGREE_WITH_DISTRIBUTION' | 'OTHER';
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      consentId: string;
      familyMemberId: string;
      familyMemberName: string;
      reason: string;
      category: 'DISPUTE' | 'NOT_INFORMED' | 'DISAGREE_WITH_DISTRIBUTION' | 'OTHER';
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

/**
 * Event: Consent Withdrawn
 */
export class ConsentWithdrawn extends DomainEvent<{
  applicationId: string;
  consentId: string;
  familyMemberId: string;
  familyMemberName: string;
  reason: string;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      consentId: string;
      familyMemberId: string;
      familyMemberName: string;
      reason: string;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

/**
 * Event: All Consents Received
 */
export class AllConsentsReceived extends DomainEvent<{
  applicationId: string;
  estateId: string;
  totalConsents: number;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      estateId: string;
      totalConsents: number;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

// ==================== COURT PROCESS EVENTS ====================

/**
 * Event: Filing Fee Paid
 */
export class FilingFeePaid extends DomainEvent<{
  applicationId: string;
  estateId: string;
  amount: number;
  paymentMethod: string;
  receiptNumber?: string;
  paidAt: Date;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      estateId: string;
      amount: number;
      paymentMethod: string;
      receiptNumber?: string;
      paidAt: Date;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

/**
 * Event: Court Rejection Received
 */
export class CourtRejectionReceived extends DomainEvent<{
  applicationId: string;
  estateId: string;
  reason: string;
  amendmentsRequired?: string[];
  rejectedAt: Date;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      estateId: string;
      reason: string;
      amendmentsRequired?: string[];
      rejectedAt: Date;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

/**
 * Event: Grant Issued
 */
export class GrantIssued extends DomainEvent<{
  applicationId: string;
  estateId: string;
  grantNumber: string;
  grantType: string;
  issuedBy: string;
  issuedAt: Date;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      estateId: string;
      grantNumber: string;
      grantType: string;
      issuedBy: string;
      issuedAt: Date;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

// ==================== ADDITIONAL EVENTS FOR COMPLETENESS ====================

/**
 * Event: Application Status Changed
 */
export class ApplicationStatusChanged extends DomainEvent<{
  applicationId: string;
  estateId: string;
  oldStatus: ApplicationStatus;
  newStatus: ApplicationStatus;
  changedAt: Date;
  reason?: string;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      estateId: string;
      oldStatus: ApplicationStatus;
      newStatus: ApplicationStatus;
      changedAt: Date;
      reason?: string;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

/**
 * Event: Priority Changed
 */
export class PriorityChanged extends DomainEvent<{
  applicationId: string;
  estateId: string;
  oldPriority: FilingPriority;
  newPriority: FilingPriority;
  changedAt: Date;
  reason: string;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      estateId: string;
      oldPriority: FilingPriority;
      newPriority: FilingPriority;
      changedAt: Date;
      reason: string;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

/**
 * Event: Gazette Published
 */
export class GazettePublished extends DomainEvent<{
  applicationId: string;
  estateId: string;
  gazetteNoticeId: string;
  publishedAt: Date;
  objectionDeadline: Date;
}> {
  constructor(
    aggregateId: string,
    aggregateType: string,
    version: number,
    payload: {
      applicationId: string;
      estateId: string;
      gazetteNoticeId: string;
      publishedAt: Date;
      objectionDeadline: Date;
    },
    occurredAt?: Date,
  ) {
    super(aggregateId, aggregateType, version, payload, occurredAt);
  }
}

// Export all events
export const ProbateApplicationEvents = {
  ProbateApplicationCreated,
  ApplicationAutoGenerated,
  ApplicationReadyToFile,
  ApplicationFiled,
  ApplicationWithdrawn,
  FormGenerated,
  FormsRegenerated,
  FormsReviewed,
  AllFormsGenerated,
  ConsentRequested,
  ConsentGranted,
  ConsentDeclined,
  ConsentWithdrawn,
  AllConsentsReceived,
  FilingFeePaid,
  CourtRejectionReceived,
  GrantIssued,
  ApplicationStatusChanged,
  PriorityChanged,
  GazettePublished,
};
