// commands/index.ts
export * from './create-will.command';
export * from './update-will.command';
export * from './assess-will-legal-capacity.command';
export * from './record-testator-signature.command';
export * from './add-will-witness.command';
export * from './record-witness-signatures.command';
export * from './mark-will-witnessed.command';
export * from './activate-will.command';
export * from './revoke-will.command';
export * from './supersede-will.command';
export * from './contest-will.command';
export * from './mark-will-executed.command';
export * from './issue-grant-probate.command';
export * from './set-will-storage.command';
export * from './enable-will-encryption.command';
export * from './remove-will-witness.command';
export * from './add-dependant-provision.command';
export * from './obtain-court-approval-provision.command';
