export class StrategyRoadmapVM {
  // Markdown content generated by StrategyGeneratorService
  strategyContent: string;

  // Key Milestones
  milestones: Array<{
    title: string;
    isCompleted: boolean;
    estimatedCompletionDate?: Date;
    blockers: string[]; // List of risk IDs blocking this milestone
  }>;

  filingFeeEstimate: number; // KES
}
