// src/family-service/src/domain/events/compliance-events.ts
import { DomainEvent } from '../base/domain-event';

/**
 * Compliance Report Submitted Event
 */
export class ComplianceReportSubmittedEvent extends DomainEvent<{
  complianceCheckId: string;
  guardianshipId: string;
  year: number;
  submissionMethod: string;
  validationScore: number;
}> {
  constructor(params: {
    complianceCheckId: string;
    guardianshipId: string;
    year: number;
    submissionMethod: string;
    validationScore: number;
  }) {
    super(
      params.complianceCheckId,
      'ComplianceCheck',
      1,
      {
        complianceCheckId: params.complianceCheckId,
        guardianshipId: params.guardianshipId,
        year: params.year,
        submissionMethod: params.submissionMethod,
        validationScore: params.validationScore,
      },
      new Date(),
    );
  }
}

/**
 * Compliance Report Accepted Event
 */
export class ComplianceReportAcceptedEvent extends DomainEvent<{
  complianceCheckId: string;
  acceptedBy: string;
  qualityScore: number;
}> {
  constructor(params: { complianceCheckId: string; acceptedBy: string; qualityScore: number }) {
    super(
      params.complianceCheckId,
      'ComplianceCheck',
      1,
      {
        complianceCheckId: params.complianceCheckId,
        acceptedBy: params.acceptedBy,
        qualityScore: params.qualityScore,
      },
      new Date(),
    );
  }
}

/**
 * Compliance Amendment Requested Event
 */
export class ComplianceAmendmentRequestedEvent extends DomainEvent<{
  complianceCheckId: string;
  feedbackType: string;
  deadline?: Date;
}> {
  constructor(params: { complianceCheckId: string; feedbackType: string; deadline?: Date }) {
    super(
      params.complianceCheckId,
      'ComplianceCheck',
      1,
      {
        complianceCheckId: params.complianceCheckId,
        feedbackType: params.feedbackType,
        deadline: params.deadline,
      },
      new Date(),
    );
  }
}

/**
 * Compliance Section Completed Event
 */
export class ComplianceSectionCompletedEvent extends DomainEvent<{
  complianceCheckId: string;
  sectionId: string;
  sectionTitle: string;
}> {
  constructor(params: { complianceCheckId: string; sectionId: string; sectionTitle: string }) {
    super(
      params.complianceCheckId,
      'ComplianceCheck',
      1,
      {
        complianceCheckId: params.complianceCheckId,
        sectionId: params.sectionId,
        sectionTitle: params.sectionTitle,
      },
      new Date(),
    );
  }
}

/**
 * Section Auto Generated Event
 */
export class SectionAutoGeneratedEvent extends DomainEvent<{
  complianceCheckId: string;
  sectionId: string;
  confidenceScore: number;
  dataSource: string;
}> {
  constructor(params: {
    complianceCheckId: string;
    sectionId: string;
    confidenceScore: number;
    dataSource: string;
  }) {
    super(
      params.complianceCheckId,
      'ComplianceCheck',
      1,
      {
        complianceCheckId: params.complianceCheckId,
        sectionId: params.sectionId,
        confidenceScore: params.confidenceScore,
        dataSource: params.dataSource,
      },
      new Date(),
    );
  }
}
