onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - argon2
  - bcrypt
  - diskusage
  - esbuild
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
