export enum KenyanCounty {
  BARINGO = 'BARINGO',
  BOMET = 'BOMET',
  BUNGOMA = 'BUNGOMA',
  BUSIA = 'BUSIA',
  ELGEYO_MARAKWET = 'ELGEYO_MARAKWET',
  EMBU = 'EMBU',
  GARISSA = 'GARISSA',
  HOMA_BAY = 'HOMA_BAY',
  ISIOLO = 'ISIOLO',
  KAJIADO = 'KAJIADO',
  KAKAMEGA = 'KAKAMEGA',
  KERICHO = 'KERICHO',
  KIAMBU = 'KIAMBU',
  KILIFI = 'KILIFI',
  KIRINYAGA = 'KIRINYAGA',
  KISII = 'KISII',
  KISUMU = 'KISUMU',
  KITUI = 'KITUI',
  KWALE = 'KWALE',
  LAIKIPIA = 'LAIKIPIA',
  LAMU = 'LAMU',
  MACHAKOS = 'MACHAKOS',
  MAKUENI = 'MAKUENI',
  MANDERA = 'MANDERA',
  MARSABIT = 'MARSABIT',
  MERU = 'MERU',
  MIGORI = 'MIGORI',
  MOMBASA = 'MOMBASA',
  MURANGA = 'MURANGA',
  NAIROBI = 'NAIROBI',
  NAKURU = 'NAKURU',
  NANDI = 'NANDI',
  NAROK = 'NAROK',
  NYAMIRA = 'NYAMIRA',
  NYANDARUA = 'NYANDARUA',
  NYERI = 'NYERI',
  SAMBURU = 'SAMBURU',
  SIAYA = 'SIAYA',
  TAITA_TAVETA = 'TAITA_TAVETA',
  TANA_RIVER = 'TANA_RIVER',
  THARAKA_NITHI = 'THARAKA_NITHI',
  TRANS_NZOIA = 'TRANS_NZOIA',
  TURKANA = 'TURKANA',
  UASIN_GISHU = 'UASIN_GISHU',
  VIHIGA = 'VIHIGA',
  WAJIR = 'WAJIR',
  WEST_POKOT = 'WEST_POKOT',
}

export class KenyanCountyValidator {
  static isValid(county: string): boolean {
    return Object.values(KenyanCounty).includes(county.toUpperCase() as KenyanCounty);
  }

  static getDisplayName(county: KenyanCounty): string {
    const displayNames: Record<KenyanCounty, string> = {
      [KenyanCounty.BARINGO]: 'Baringo',
      [KenyanCounty.BOMET]: 'Bomet',
      [KenyanCounty.BUNGOMA]: 'Bungoma',
      [KenyanCounty.BUSIA]: 'Busia',
      [KenyanCounty.ELGEYO_MARAKWET]: 'Elgeyo Marakwet',
      [KenyanCounty.EMBU]: 'Embu',
      [KenyanCounty.GARISSA]: 'Garissa',
      [KenyanCounty.HOMA_BAY]: 'Homa Bay',
      [KenyanCounty.ISIOLO]: 'Isiolo',
      [KenyanCounty.KAJIADO]: 'Kajiado',
      [KenyanCounty.KAKAMEGA]: 'Kakamega',
      [KenyanCounty.KERICHO]: 'Kericho',
      [KenyanCounty.KIAMBU]: 'Kiambu',
      [KenyanCounty.KILIFI]: 'Kilifi',
      [KenyanCounty.KIRINYAGA]: 'Kirinyaga',
      [KenyanCounty.KISII]: 'Kisii',
      [KenyanCounty.KISUMU]: 'Kisumu',
      [KenyanCounty.KITUI]: 'Kitui',
      [KenyanCounty.KWALE]: 'Kwale',
      [KenyanCounty.LAIKIPIA]: 'Laikipia',
      [KenyanCounty.LAMU]: 'Lamu',
      [KenyanCounty.MACHAKOS]: 'Machakos',
      [KenyanCounty.MAKUENI]: 'Makueni',
      [KenyanCounty.MANDERA]: 'Mandera',
      [KenyanCounty.MARSABIT]: 'Marsabit',
      [KenyanCounty.MERU]: 'Meru',
      [KenyanCounty.MIGORI]: 'Migori',
      [KenyanCounty.MOMBASA]: 'Mombasa',
      [KenyanCounty.MURANGA]: "Murang'a",
      [KenyanCounty.NAIROBI]: 'Nairobi',
      [KenyanCounty.NAKURU]: 'Nakuru',
      [KenyanCounty.NANDI]: 'Nandi',
      [KenyanCounty.NAROK]: 'Narok',
      [KenyanCounty.NYAMIRA]: 'Nyamira',
      [KenyanCounty.NYANDARUA]: 'Nyandarua',
      [KenyanCounty.NYERI]: 'Nyeri',
      [KenyanCounty.SAMBURU]: 'Samburu',
      [KenyanCounty.SIAYA]: 'Siaya',
      [KenyanCounty.TAITA_TAVETA]: 'Taita Taveta',
      [KenyanCounty.TANA_RIVER]: 'Tana River',
      [KenyanCounty.THARAKA_NITHI]: 'Tharaka Nithi',
      [KenyanCounty.TRANS_NZOIA]: 'Trans Nzoia',
      [KenyanCounty.TURKANA]: 'Turkana',
      [KenyanCounty.UASIN_GISHU]: 'Uasin Gishu',
      [KenyanCounty.VIHIGA]: 'Vihiga',
      [KenyanCounty.WAJIR]: 'Wajir',
      [KenyanCounty.WEST_POKOT]: 'West Pokot',
    };
    return displayNames[county] || county;
  }

  static getCountyCode(county: KenyanCounty): string {
    const countyCodes: Record<KenyanCounty, string> = {
      [KenyanCounty.BARINGO]: '01',
      [KenyanCounty.BOMET]: '02',
      [KenyanCounty.BUNGOMA]: '03',
      [KenyanCounty.BUSIA]: '04',
      [KenyanCounty.ELGEYO_MARAKWET]: '05',
      [KenyanCounty.EMBU]: '06',
      [KenyanCounty.GARISSA]: '07',
      [KenyanCounty.HOMA_BAY]: '08',
      [KenyanCounty.ISIOLO]: '09',
      [KenyanCounty.KAJIADO]: '10',
      [KenyanCounty.KAKAMEGA]: '11',
      [KenyanCounty.KERICHO]: '12',
      [KenyanCounty.KIAMBU]: '13',
      [KenyanCounty.KILIFI]: '14',
      [KenyanCounty.KIRINYAGA]: '15',
      [KenyanCounty.KISII]: '16',
      [KenyanCounty.KISUMU]: '17',
      [KenyanCounty.KITUI]: '18',
      [KenyanCounty.KWALE]: '19',
      [KenyanCounty.LAIKIPIA]: '20',
      [KenyanCounty.LAMU]: '21',
      [KenyanCounty.MACHAKOS]: '22',
      [KenyanCounty.MAKUENI]: '23',
      [KenyanCounty.MANDERA]: '24',
      [KenyanCounty.MARSABIT]: '25',
      [KenyanCounty.MERU]: '26',
      [KenyanCounty.MIGORI]: '27',
      [KenyanCounty.MOMBASA]: '28',
      [KenyanCounty.MURANGA]: '29',
      [KenyanCounty.NAIROBI]: '30',
      [KenyanCounty.NAKURU]: '31',
      [KenyanCounty.NANDI]: '32',
      [KenyanCounty.NAROK]: '33',
      [KenyanCounty.NYAMIRA]: '34',
      [KenyanCounty.NYANDARUA]: '35',
      [KenyanCounty.NYERI]: '36',
      [KenyanCounty.SAMBURU]: '37',
      [KenyanCounty.SIAYA]: '38',
      [KenyanCounty.TAITA_TAVETA]: '39',
      [KenyanCounty.TANA_RIVER]: '40',
      [KenyanCounty.THARAKA_NITHI]: '41',
      [KenyanCounty.TRANS_NZOIA]: '42',
      [KenyanCounty.TURKANA]: '43',
      [KenyanCounty.UASIN_GISHU]: '44',
      [KenyanCounty.VIHIGA]: '45',
      [KenyanCounty.WAJIR]: '46',
      [KenyanCounty.WEST_POKOT]: '47',
    };
    return countyCodes[county] || '00';
  }

  static getRegion(county: KenyanCounty): string {
    const regions: Record<KenyanCounty, string> = {
      [KenyanCounty.BARINGO]: 'Rift Valley',
      [KenyanCounty.BOMET]: 'Rift Valley',
      [KenyanCounty.BUNGOMA]: 'Western',
      [KenyanCounty.BUSIA]: 'Western',
      [KenyanCounty.ELGEYO_MARAKWET]: 'Rift Valley',
      [KenyanCounty.EMBU]: 'Eastern',
      [KenyanCounty.GARISSA]: 'North Eastern',
      [KenyanCounty.HOMA_BAY]: 'Nyanza',
      [KenyanCounty.ISIOLO]: 'Eastern',
      [KenyanCounty.KAJIADO]: 'Rift Valley',
      [KenyanCounty.KAKAMEGA]: 'Western',
      [KenyanCounty.KERICHO]: 'Rift Valley',
      [KenyanCounty.KIAMBU]: 'Central',
      [KenyanCounty.KILIFI]: 'Coast',
      [KenyanCounty.KIRINYAGA]: 'Central',
      [KenyanCounty.KISII]: 'Nyanza',
      [KenyanCounty.KISUMU]: 'Nyanza',
      [KenyanCounty.KITUI]: 'Eastern',
      [KenyanCounty.KWALE]: 'Coast',
      [KenyanCounty.LAIKIPIA]: 'Rift Valley',
      [KenyanCounty.LAMU]: 'Coast',
      [KenyanCounty.MACHAKOS]: 'Eastern',
      [KenyanCounty.MAKUENI]: 'Eastern',
      [KenyanCounty.MANDERA]: 'North Eastern',
      [KenyanCounty.MARSABIT]: 'Eastern',
      [KenyanCounty.MERU]: 'Eastern',
      [KenyanCounty.MIGORI]: 'Nyanza',
      [KenyanCounty.MOMBASA]: 'Coast',
      [KenyanCounty.MURANGA]: 'Central',
      [KenyanCounty.NAIROBI]: 'Nairobi',
      [KenyanCounty.NAKURU]: 'Rift Valley',
      [KenyanCounty.NANDI]: 'Rift Valley',
      [KenyanCounty.NAROK]: 'Rift Valley',
      [KenyanCounty.NYAMIRA]: 'Nyanza',
      [KenyanCounty.NYANDARUA]: 'Central',
      [KenyanCounty.NYERI]: 'Central',
      [KenyanCounty.SAMBURU]: 'Rift Valley',
      [KenyanCounty.SIAYA]: 'Nyanza',
      [KenyanCounty.TAITA_TAVETA]: 'Coast',
      [KenyanCounty.TANA_RIVER]: 'Coast',
      [KenyanCounty.THARAKA_NITHI]: 'Eastern',
      [KenyanCounty.TRANS_NZOIA]: 'Rift Valley',
      [KenyanCounty.TURKANA]: 'Rift Valley',
      [KenyanCounty.UASIN_GISHU]: 'Rift Valley',
      [KenyanCounty.VIHIGA]: 'Western',
      [KenyanCounty.WAJIR]: 'North Eastern',
      [KenyanCounty.WEST_POKOT]: 'Rift Valley',
    };
    return regions[county] || 'Unknown';
  }

  static getNeighboringCounties(county: KenyanCounty): KenyanCounty[] {
    const neighbors: Record<KenyanCounty, KenyanCounty[]> = {
      [KenyanCounty.BARINGO]: [
        KenyanCounty.LAIKIPIA,
        KenyanCounty.SAMBURU,
        KenyanCounty.TURKANA,
        KenyanCounty.WEST_POKOT,
        KenyanCounty.ELGEYO_MARAKWET,
      ],
      [KenyanCounty.BOMET]: [
        KenyanCounty.KERICHO,
        KenyanCounty.NAROK,
        KenyanCounty.NYAMIRA,
        KenyanCounty.KISII,
      ],
      [KenyanCounty.BUNGOMA]: [KenyanCounty.KAKAMEGA, KenyanCounty.TRANS_NZOIA, KenyanCounty.BUSIA],
      [KenyanCounty.BUSIA]: [KenyanCounty.BUNGOMA, KenyanCounty.SIAYA],
      [KenyanCounty.ELGEYO_MARAKWET]: [
        KenyanCounty.BARINGO,
        KenyanCounty.TRANS_NZOIA,
        KenyanCounty.WEST_POKOT,
        KenyanCounty.NAKURU,
      ],
      [KenyanCounty.EMBU]: [KenyanCounty.KIRINYAGA, KenyanCounty.MERU, KenyanCounty.THARAKA_NITHI],
      [KenyanCounty.GARISSA]: [KenyanCounty.WAJIR, KenyanCounty.TANA_RIVER, KenyanCounty.LAMU],
      [KenyanCounty.HOMA_BAY]: [
        KenyanCounty.KISII,
        KenyanCounty.MIGORI,
        KenyanCounty.KISUMU,
        KenyanCounty.SIAYA,
      ],
      [KenyanCounty.ISIOLO]: [
        KenyanCounty.MARSABIT,
        KenyanCounty.MERU,
        KenyanCounty.LAIKIPIA,
        KenyanCounty.SAMBURU,
      ],
      [KenyanCounty.KAJIADO]: [
        KenyanCounty.NAKURU,
        KenyanCounty.NAROK,
        KenyanCounty.KIAMBU,
        KenyanCounty.MAKUENI,
      ],
      [KenyanCounty.KAKAMEGA]: [KenyanCounty.BUNGOMA, KenyanCounty.VIHIGA, KenyanCounty.SIAYA],
      [KenyanCounty.KERICHO]: [
        KenyanCounty.BOMET,
        KenyanCounty.NAROK,
        KenyanCounty.NAKURU,
        KenyanCounty.NYAMIRA,
      ],
      [KenyanCounty.KIAMBU]: [
        KenyanCounty.NAIROBI,
        KenyanCounty.NYANDARUA,
        KenyanCounty.MURANGA,
        KenyanCounty.NYERI,
        KenyanCounty.KAJIADO,
      ],
      [KenyanCounty.KILIFI]: [
        KenyanCounty.MOMBASA,
        KenyanCounty.TAITA_TAVETA,
        KenyanCounty.TANA_RIVER,
      ],
      [KenyanCounty.KIRINYAGA]: [KenyanCounty.EMBU, KenyanCounty.MURANGA, KenyanCounty.NYERI],
      [KenyanCounty.KISII]: [KenyanCounty.BOMET, KenyanCounty.HOMA_BAY, KenyanCounty.NYAMIRA],
      [KenyanCounty.KISUMU]: [KenyanCounty.HOMA_BAY, KenyanCounty.SIAYA, KenyanCounty.VIHIGA],
      [KenyanCounty.KITUI]: [
        KenyanCounty.MACHAKOS,
        KenyanCounty.MAKUENI,
        KenyanCounty.EMBU,
        KenyanCounty.THARAKA_NITHI,
      ],
      [KenyanCounty.KWALE]: [KenyanCounty.MOMBASA, KenyanCounty.TAITA_TAVETA],
      [KenyanCounty.LAIKIPIA]: [
        KenyanCounty.BARINGO,
        KenyanCounty.ISIOLO,
        KenyanCounty.MERU,
        KenyanCounty.NAKURU,
        KenyanCounty.NYANDARUA,
        KenyanCounty.SAMBURU,
      ],
      [KenyanCounty.LAMU]: [KenyanCounty.GARISSA, KenyanCounty.TANA_RIVER],
      [KenyanCounty.MACHAKOS]: [
        KenyanCounty.KAJIADO,
        KenyanCounty.KITUI,
        KenyanCounty.MAKUENI,
        KenyanCounty.NAIROBI,
      ],
      [KenyanCounty.MAKUENI]: [
        KenyanCounty.KAJIADO,
        KenyanCounty.KITUI,
        KenyanCounty.MACHAKOS,
        KenyanCounty.TAITA_TAVETA,
      ],
      [KenyanCounty.MANDERA]: [KenyanCounty.WAJIR],
      [KenyanCounty.MARSABIT]: [KenyanCounty.ISIOLO, KenyanCounty.SAMBURU, KenyanCounty.TURKANA],
      [KenyanCounty.MERU]: [
        KenyanCounty.EMBU,
        KenyanCounty.ISIOLO,
        KenyanCounty.LAIKIPIA,
        KenyanCounty.THARAKA_NITHI,
      ],
      [KenyanCounty.MIGORI]: [KenyanCounty.HOMA_BAY, KenyanCounty.KISII, KenyanCounty.NAROK],
      [KenyanCounty.MOMBASA]: [KenyanCounty.KILIFI, KenyanCounty.KWALE],
      [KenyanCounty.MURANGA]: [
        KenyanCounty.KIAMBU,
        KenyanCounty.KIRINYAGA,
        KenyanCounty.NYANDARUA,
        KenyanCounty.NYERI,
      ],
      [KenyanCounty.NAIROBI]: [KenyanCounty.KIAMBU, KenyanCounty.MACHAKOS],
      [KenyanCounty.NAKURU]: [
        KenyanCounty.BARINGO,
        KenyanCounty.KAJIADO,
        KenyanCounty.KERICHO,
        KenyanCounty.LAIKIPIA,
        KenyanCounty.NAROK,
        KenyanCounty.NYANDARUA,
      ],
      [KenyanCounty.NANDI]: [KenyanCounty.KAKAMEGA, KenyanCounty.KERICHO, KenyanCounty.VIHIGA],
      [KenyanCounty.NAROK]: [
        KenyanCounty.BOMET,
        KenyanCounty.KAJIADO,
        KenyanCounty.KERICHO,
        KenyanCounty.MIGORI,
        KenyanCounty.NAKURU,
      ],
      [KenyanCounty.NYAMIRA]: [KenyanCounty.BOMET, KenyanCounty.KERICHO, KenyanCounty.KISII],
      [KenyanCounty.NYANDARUA]: [
        KenyanCounty.KIAMBU,
        KenyanCounty.LAIKIPIA,
        KenyanCounty.MURANGA,
        KenyanCounty.NAKURU,
        KenyanCounty.NYERI,
      ],
      [KenyanCounty.NYERI]: [
        KenyanCounty.KIAMBU,
        KenyanCounty.KIRINYAGA,
        KenyanCounty.MURANGA,
        KenyanCounty.NYANDARUA,
      ],
      [KenyanCounty.SAMBURU]: [
        KenyanCounty.BARINGO,
        KenyanCounty.ISIOLO,
        KenyanCounty.LAIKIPIA,
        KenyanCounty.MARSABIT,
        KenyanCounty.TURKANA,
      ],
      [KenyanCounty.SIAYA]: [
        KenyanCounty.BUSIA,
        KenyanCounty.HOMA_BAY,
        KenyanCounty.KAKAMEGA,
        KenyanCounty.KISUMU,
        KenyanCounty.VIHIGA,
      ],
      [KenyanCounty.TAITA_TAVETA]: [KenyanCounty.KILIFI, KenyanCounty.KWALE, KenyanCounty.MAKUENI],
      [KenyanCounty.TANA_RIVER]: [KenyanCounty.GARISSA, KenyanCounty.KILIFI, KenyanCounty.LAMU],
      [KenyanCounty.THARAKA_NITHI]: [KenyanCounty.EMBU, KenyanCounty.KITUI, KenyanCounty.MERU],
      [KenyanCounty.TRANS_NZOIA]: [
        KenyanCounty.BUNGOMA,
        KenyanCounty.ELGEYO_MARAKWET,
        KenyanCounty.WEST_POKOT,
      ],
      [KenyanCounty.TURKANA]: [
        KenyanCounty.BARINGO,
        KenyanCounty.MARSABIT,
        KenyanCounty.SAMBURU,
        KenyanCounty.WEST_POKOT,
      ],
      [KenyanCounty.UASIN_GISHU]: [
        KenyanCounty.ELGEYO_MARAKWET,
        KenyanCounty.NANDI,
        KenyanCounty.TRANS_NZOIA,
      ],
      [KenyanCounty.VIHIGA]: [KenyanCounty.KAKAMEGA, KenyanCounty.NANDI, KenyanCounty.SIAYA],
      [KenyanCounty.WAJIR]: [KenyanCounty.GARISSA, KenyanCounty.MANDERA],
      [KenyanCounty.WEST_POKOT]: [
        KenyanCounty.BARINGO,
        KenyanCounty.ELGEYO_MARAKWET,
        KenyanCounty.TRANS_NZOIA,
        KenyanCounty.TURKANA,
      ],
    };
    return neighbors[county] || [];
  }

  static getAllCounties(): KenyanCounty[] {
    return Object.values(KenyanCounty);
  }

  static getCountiesByRegion(region: string): KenyanCounty[] {
    const counties = this.getAllCounties();
    return counties.filter((county) => this.getRegion(county) === region);
  }
}
