// domain/entities/compliance-check.entity.ts
import { Entity } from '../base/entity';
import { UniqueEntityID } from '../base/unique-entity-id';
import { InvalidGuardianshipException } from '../exceptions/guardianship.exception';

/**
 * Compliance Check Status (S.73 LSA)
 * Tracks annual report filing status for guardians managing property
 */
export enum ComplianceCheckStatus {
  PENDING = 'PENDING', // Not yet due for filing
  DUE = 'DUE', // Due now for filing
  SUBMITTED = 'SUBMITTED', // Filed, awaiting court review
  APPROVED = 'APPROVED', // Court approved the report
  OVERDUE = 'OVERDUE', // Past deadline - non-compliant
  REJECTED = 'REJECTED', // Court rejected - resubmit required
  WAIVED = 'WAIVED', // Court waived the requirement
  EXTENDED = 'EXTENDED', // Court granted extension
}

/**
 * Compliance Check Entity Props
 * Represents an annual compliance filing requirement for a guardianship
 */
export interface ComplianceCheckProps {
  // === CORE IDENTITY ===
  guardianId: string;
  year: number; // The financial year this check covers

  // === FILING DETAILS ===
  filingDate?: Date; // When the report was actually filed
  status: ComplianceCheckStatus; // Current status of the check

  // === COMPLIANCE DOCUMENTATION ===
  notes?: string; // Any notes from the court or guardian
  reportDocumentId?: string; // Reference to the filed document (from documents-service)

  // === COURT REVIEW ===
  reviewedBy?: UniqueEntityID; // Who reviewed this (court officer)
  reviewedAt?: Date; // When it was reviewed
  reviewComments?: string; // Court's comments on the report

  // === EXTENSIONS & WAIVERS ===
  extensionReason?: string; // Reason for extension if granted
  extensionGrantedBy?: UniqueEntityID; // Who granted the extension
  extensionGrantedAt?: Date; // When extension was granted
  originalDeadline?: Date; // Original deadline before extension
  newDeadline?: Date; // New deadline after extension

  waiverReason?: string; // Reason for waiver if granted
  waiverGrantedBy?: UniqueEntityID; // Who granted the waiver
  waiverGrantedAt?: Date; // When waiver was granted

  // === FINANCIAL DETAILS (If applicable) ===
  assetsUnderManagementKES?: number; // Value of assets being managed
  guardianExpensesKES?: number; // Expenses incurred by guardian
  guardianAllowanceKES?: number; // Allowance paid to guardian
  estateIncomeKES?: number; // Income generated by the estate
  estateExpensesKES?: number; // Expenses of the estate
}

/**
 * Props for Creating Compliance Check
 */
export interface CreateComplianceCheckProps {
  guardianId: string;
  year: number;
  status?: ComplianceCheckStatus;

  // Optional details for pre-filing or existing checks
  filingDate?: Date;
  notes?: string;
  reportDocumentId?: string;
  assetsUnderManagementKES?: number;
}

/**
 * COMPLIANCE CHECK ENTITY
 *
 * Represents an annual compliance filing requirement under S.73 LSA
 * for guardians who manage property on behalf of wards.
 *
 * LEGAL BASIS: S.73 Law of Succession Act (Kenya)
 * "Every guardian shall within 60 days after expiration of each year
 * render to the court full and accurate accounts of his management
 * of the estate of the minor during that year."
 *
 * IMPORTANT: This is an ENTITY, not an Aggregate Root
 * It belongs to the Guardianship aggregate and cannot exist independently
 *
 * TIMING: Reports are due within 60 days after each year of guardianship
 * DEADLINE: 60 days after anniversary of guardianship start
 *
 * INVARIANTS:
 * - Year must be current or future (can't file for past years without court approval)
 * - Status transitions must follow legal workflow
 * - Filed reports must have a filing date
 * - Approved reports must have review details
 * - Extensions must be granted before deadline
 */
export class ComplianceCheck extends Entity<ComplianceCheckProps> {
  private constructor(id: UniqueEntityID, props: ComplianceCheckProps, createdAt?: Date) {
    super(id, props, createdAt);
    this.validate();
  }

  // ============================================================================
  // FACTORY METHODS
  // ============================================================================

  /**
   * Create new Compliance Check for a given year
   * Typically created automatically when guardianship starts or at year-end
   */
  public static create(props: CreateComplianceCheckProps): ComplianceCheck {
    const id = new UniqueEntityID();

    // Validate year is reasonable (current year +/- 1)
    const currentYear = new Date().getFullYear();
    if (props.year < currentYear - 1 || props.year > currentYear + 1) {
      console.warn(
        `Creating compliance check for year ${props.year} which is outside normal range (${currentYear - 1}-${currentYear + 1})`,
      );
    }

    return new ComplianceCheck(id, {
      guardianId: props.guardianId,
      year: props.year,
      status: props.status || ComplianceCheckStatus.PENDING,
      filingDate: props.filingDate,
      notes: props.notes,
      reportDocumentId: props.reportDocumentId,
      assetsUnderManagementKES: props.assetsUnderManagementKES,
    });
  }

  /**
   * Reconstitute from database (existing compliance check)
   */
  public static fromPersistence(
    id: string,
    props: ComplianceCheckProps,
    createdAt: Date,
  ): ComplianceCheck {
    return new ComplianceCheck(new UniqueEntityID(id), props, createdAt);
  }

  // ============================================================================
  // DOMAIN LOGIC - FILING REPORTS
  // ============================================================================

  /**
   * File Annual Report (S.73 LSA Requirement)
   *
   * LEGAL REQUIREMENT:
   * - Must be filed within 60 days after expiration of each year
   * - Must include full and accurate accounts
   * - Must be submitted to court for approval
   */
  public fileReport(params: {
    filingDate: Date;
    reportDocumentId: string;
    notes?: string;
    assetsUnderManagementKES?: number;
    guardianExpensesKES?: number;
    guardianAllowanceKES?: number;
    estateIncomeKES?: number;
    estateExpensesKES?: number;
  }): void {
    this.ensureNotDeleted();

    // Validation
    if (!this.isDue() && !this.isOverdue()) {
      throw new InvalidGuardianshipException(
        `Cannot file report for year ${this.props.year} - it is not yet due. Status: ${this.props.status}`,
      );
    }

    if (params.filingDate > new Date()) {
      throw new InvalidGuardianshipException('Filing date cannot be in the future.');
    }

    // Check if already filed (but allow re-filing if rejected)
    if (
      this.props.status === ComplianceCheckStatus.SUBMITTED ||
      this.props.status === ComplianceCheckStatus.APPROVED
    ) {
      throw new InvalidGuardianshipException(
        `Report for year ${this.props.year} has already been ${this.props.status.toLowerCase()}.`,
      );
    }

    const newProps = {
      ...this.cloneProps(),
      filingDate: params.filingDate,
      reportDocumentId: params.reportDocumentId,
      status: ComplianceCheckStatus.SUBMITTED,
      notes: params.notes,
      assetsUnderManagementKES: params.assetsUnderManagementKES,
      guardianExpensesKES: params.guardianExpensesKES,
      guardianAllowanceKES: params.guardianAllowanceKES,
      estateIncomeKES: params.estateIncomeKES,
      estateExpensesKES: params.estateExpensesKES,
    };

    (this as any)._props = Object.freeze(newProps);
    this.incrementVersion();
  }

  /**
   * Court Review of Submitted Report
   *
   * This is the court's decision on the filed report
   */
  public reviewReport(params: {
    approved: boolean;
    reviewedBy: string;
    reviewComments?: string;
    reviewedAt?: Date;
  }): void {
    this.ensureNotDeleted();

    if (this.props.status !== ComplianceCheckStatus.SUBMITTED) {
      throw new InvalidGuardianshipException(
        `Cannot review report for year ${this.props.year} - it is not in SUBMITTED status. Current status: ${this.props.status}`,
      );
    }

    const newStatus = params.approved
      ? ComplianceCheckStatus.APPROVED
      : ComplianceCheckStatus.REJECTED;

    const newProps = {
      ...this.cloneProps(),
      status: newStatus,
      reviewedBy: new UniqueEntityID(params.reviewedBy),
      reviewedAt: params.reviewedAt || new Date(),
      reviewComments: params.reviewComments,
    };

    (this as any)._props = Object.freeze(newProps);
    this.incrementVersion();
  }

  // ============================================================================
  // DOMAIN LOGIC - EXTENSIONS & WAIVERS
  // ============================================================================

  /**
   * Request Extension for Filing Deadline
   *
   * Court can grant extensions under special circumstances
   * (e.g., illness, complex estate, etc.)
   */
  public grantExtension(params: {
    newDeadline: Date;
    reason: string;
    grantedBy: string;
    grantedAt?: Date;
  }): void {
    this.ensureNotDeleted();

    // Validation
    if (params.newDeadline <= new Date()) {
      throw new InvalidGuardianshipException('New deadline must be in the future.');
    }

    if (
      this.props.status !== ComplianceCheckStatus.PENDING &&
      this.props.status !== ComplianceCheckStatus.DUE
    ) {
      throw new InvalidGuardianshipException(
        `Cannot grant extension for report in status: ${this.props.status}`,
      );
    }

    const newProps = {
      ...this.cloneProps(),
      status: ComplianceCheckStatus.EXTENDED,
      extensionReason: params.reason,
      extensionGrantedBy: new UniqueEntityID(params.grantedBy),
      extensionGrantedAt: params.grantedAt || new Date(),
      originalDeadline: this.props.originalDeadline || this.calculateDefaultDeadline(),
      newDeadline: params.newDeadline,
    };

    (this as any)._props = Object.freeze(newProps);
    this.incrementVersion();
  }

  /**
   * Grant Waiver from Filing Requirement
   *
   * Court can waive reporting requirement under special circumstances
   * (e.g., minimal assets, hardship, etc.)
   */
  public grantWaiver(params: { reason: string; grantedBy: string; grantedAt?: Date }): void {
    this.ensureNotDeleted();

    if (
      this.props.status !== ComplianceCheckStatus.PENDING &&
      this.props.status !== ComplianceCheckStatus.DUE
    ) {
      throw new InvalidGuardianshipException(
        `Cannot grant waiver for report in status: ${this.props.status}`,
      );
    }

    const newProps = {
      ...this.cloneProps(),
      status: ComplianceCheckStatus.WAIVED,
      waiverReason: params.reason,
      waiverGrantedBy: new UniqueEntityID(params.grantedBy),
      waiverGrantedAt: params.grantedAt || new Date(),
    };

    (this as any)._props = Object.freeze(newProps);
    this.incrementVersion();
  }

  // ============================================================================
  // DOMAIN LOGIC - STATUS UPDATES
  // ============================================================================

  /**
   * Mark as Due (when deadline arrives)
   * This would typically be called by a scheduled job
   */
  public markAsDue(): void {
    this.ensureNotDeleted();

    if (this.props.status !== ComplianceCheckStatus.PENDING) {
      throw new InvalidGuardianshipException(
        `Cannot mark as DUE - current status is ${this.props.status}`,
      );
    }

    const newProps = {
      ...this.cloneProps(),
      status: ComplianceCheckStatus.DUE,
    };

    (this as any)._props = Object.freeze(newProps);
    this.incrementVersion();
  }

  /**
   * Mark as Overdue (when deadline passes)
   * This would typically be called by a scheduled job
   */
  public markAsOverdue(): void {
    this.ensureNotDeleted();

    if (
      this.props.status !== ComplianceCheckStatus.DUE &&
      this.props.status !== ComplianceCheckStatus.EXTENDED
    ) {
      throw new InvalidGuardianshipException(
        `Cannot mark as OVERDUE - current status is ${this.props.status}`,
      );
    }

    const newProps = {
      ...this.cloneProps(),
      status: ComplianceCheckStatus.OVERDUE,
    };

    (this as any)._props = Object.freeze(newProps);
    this.incrementVersion();
  }

  /**
   * Resubmit Report (after rejection)
   */
  public resubmitReport(params: {
    filingDate: Date;
    reportDocumentId: string;
    notes?: string;
  }): void {
    this.ensureNotDeleted();

    if (this.props.status !== ComplianceCheckStatus.REJECTED) {
      throw new InvalidGuardianshipException(
        `Cannot resubmit report - current status is ${this.props.status}`,
      );
    }

    const newProps = {
      ...this.cloneProps(),
      status: ComplianceCheckStatus.SUBMITTED,
      filingDate: params.filingDate,
      reportDocumentId: params.reportDocumentId,
      notes: params.notes,
    };

    (this as any)._props = Object.freeze(newProps);
    this.incrementVersion();
  }

  // ============================================================================
  // VALIDATION
  // ============================================================================

  private validate(): void {
    // Year validation
    const currentYear = new Date().getFullYear();
    if (this.props.year < 1900 || this.props.year > currentYear + 10) {
      throw new InvalidGuardianshipException(
        `Invalid year for compliance check: ${this.props.year}`,
      );
    }

    // Status-specific validation
    if (
      this.props.status === ComplianceCheckStatus.SUBMITTED ||
      this.props.status === ComplianceCheckStatus.APPROVED
    ) {
      if (!this.props.filingDate) {
        throw new InvalidGuardianshipException(
          `Compliance check in status ${this.props.status} must have a filing date`,
        );
      }
      if (!this.props.reportDocumentId) {
        console.warn(
          `Compliance check ${this._id.toString()} is ${this.props.status} but has no report document ID`,
        );
      }
    }

    if (this.props.status === ComplianceCheckStatus.APPROVED) {
      if (!this.props.reviewedBy || !this.props.reviewedAt) {
        console.warn(
          `Compliance check ${this._id.toString()} is APPROVED but missing review details`,
        );
      }
    }

    if (this.props.status === ComplianceCheckStatus.EXTENDED) {
      if (!this.props.extensionGrantedBy || !this.props.newDeadline) {
        throw new InvalidGuardianshipException(
          'EXTENDED compliance check must have extension details',
        );
      }
    }

    if (this.props.status === ComplianceCheckStatus.WAIVED) {
      if (!this.props.waiverGrantedBy) {
        throw new InvalidGuardianshipException('WAIVED compliance check must have waiver details');
      }
    }

    // Financial data validation
    this.validateFinancialData();
  }

  private validateFinancialData(): void {
    const financialFields = [
      'assetsUnderManagementKES',
      'guardianExpensesKES',
      'guardianAllowanceKES',
      'estateIncomeKES',
      'estateExpensesKES',
    ] as const;

    for (const field of financialFields) {
      const value = this.props[field];
      if (value !== undefined && value < 0) {
        throw new InvalidGuardianshipException(`${field} cannot be negative`);
      }
    }
  }

  // ============================================================================
  // QUERY METHODS (GETTERS)
  // ============================================================================

  get year(): number {
    return this.props.year;
  }

  get status(): ComplianceCheckStatus {
    return this.props.status;
  }

  get filingDate(): Date | undefined {
    return this.props.filingDate;
  }

  get reportDocumentId(): string | undefined {
    return this.props.reportDocumentId;
  }

  /**
   * Check if this compliance check is due for filing
   */
  public isDue(): boolean {
    return this.props.status === ComplianceCheckStatus.DUE;
  }

  /**
   * Check if this compliance check is overdue
   */
  public isOverdue(): boolean {
    return this.props.status === ComplianceCheckStatus.OVERDUE;
  }

  /**
   * Check if this compliance check has been filed
   */
  public isFiled(): boolean {
    return [
      ComplianceCheckStatus.SUBMITTED,
      ComplianceCheckStatus.APPROVED,
      ComplianceCheckStatus.REJECTED,
    ].includes(this.props.status);
  }

  /**
   * Check if this compliance check is compliant
   * (Filed and approved, or waived/not required)
   */
  public isCompliant(): boolean {
    return [ComplianceCheckStatus.APPROVED, ComplianceCheckStatus.WAIVED].includes(
      this.props.status,
    );
  }

  /**
   * Check if this compliance check requires action
   */
  public requiresAction(): boolean {
    return [
      ComplianceCheckStatus.DUE,
      ComplianceCheckStatus.OVERDUE,
      ComplianceCheckStatus.REJECTED,
    ].includes(this.props.status);
  }

  /**
   * Calculate the default deadline for this report
   * (60 days after the year ends)
   */
  public calculateDefaultDeadline(): Date {
    // Assuming report is for calendar year ending Dec 31
    const deadline = new Date(this.props.year, 2, 1); // March 1 of following year (60 days after Dec 31)
    return deadline;
  }

  /**
   * Get current deadline (takes extensions into account)
   */
  public getCurrentDeadline(): Date {
    if (this.props.newDeadline) {
      return this.props.newDeadline;
    }
    return this.calculateDefaultDeadline();
  }

  /**
   * Get days until deadline (negative if overdue)
   */
  public getDaysUntilDeadline(): number {
    const deadline = this.getCurrentDeadline();
    const today = new Date();
    const diffTime = deadline.getTime() - today.getTime();
    return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  }

  // ============================================================================
  // HELPER METHODS
  // ============================================================================

  /**
   * Calculate financial summary for this compliance period
   */
  public calculateFinancialSummary(): Record<string, any> {
    return {
      assetsUnderManagementKES: this.props.assetsUnderManagementKES || 0,
      guardianExpensesKES: this.props.guardianExpensesKES || 0,
      guardianAllowanceKES: this.props.guardianAllowanceKES || 0,
      estateIncomeKES: this.props.estateIncomeKES || 0,
      estateExpensesKES: this.props.estateExpensesKES || 0,
      netEstateChangeKES: (this.props.estateIncomeKES || 0) - (this.props.estateExpensesKES || 0),
      totalGuardianCostKES:
        (this.props.guardianExpensesKES || 0) + (this.props.guardianAllowanceKES || 0),
    };
  }

  /**
   * Serialize to JSON for API responses
   */
  public toJSON(): Record<string, any> {
    const financialSummary = this.calculateFinancialSummary();

    return {
      id: this._id.toString(),
      guardianId: this.props.guardianId,
      year: this.props.year,
      status: this.props.status,
      filingDate: this.props.filingDate?.toISOString(),
      reportDocumentId: this.props.reportDocumentId,
      notes: this.props.notes,
      reviewedBy: this.props.reviewedBy?.toString(),
      reviewedAt: this.props.reviewedAt?.toISOString(),
      reviewComments: this.props.reviewComments,
      extensionReason: this.props.extensionReason,
      extensionGrantedBy: this.props.extensionGrantedBy?.toString(),
      extensionGrantedAt: this.props.extensionGrantedAt?.toISOString(),
      originalDeadline: this.props.originalDeadline?.toISOString(),
      newDeadline: this.props.newDeadline?.toISOString(),
      waiverReason: this.props.waiverReason,
      waiverGrantedBy: this.props.waiverGrantedBy?.toString(),
      waiverGrantedAt: this.props.waiverGrantedAt?.toISOString(),

      // Financial data
      assetsUnderManagementKES: this.props.assetsUnderManagementKES,
      guardianExpensesKES: this.props.guardianExpensesKES,
      guardianAllowanceKES: this.props.guardianAllowanceKES,
      estateIncomeKES: this.props.estateIncomeKES,
      estateExpensesKES: this.props.estateExpensesKES,
      financialSummary,

      // Computed properties
      isDue: this.isDue(),
      isOverdue: this.isOverdue(),
      isFiled: this.isFiled(),
      isCompliant: this.isCompliant(),
      requiresAction: this.requiresAction(),
      currentDeadline: this.getCurrentDeadline().toISOString(),
      daysUntilDeadline: this.getDaysUntilDeadline(),

      // Metadata
      version: this._version,
      createdAt: this._createdAt.toISOString(),
      updatedAt: this._updatedAt.toISOString(),
      deletedAt: this._deletedAt?.toISOString(),
    };
  }
}
