// src/domain/interfaces/repositories/iguardianship.repository.ts
import { GuardianshipAggregate } from '../../aggregates/guardianship.aggregate';
import { DomainEvent } from '../../base/domain-event';

/**
 * Enhanced Pagination with Performance Metrics
 */
export interface PaginationOptions {
  page: number; // 1-indexed
  pageSize: number; // Items per page
  includeCount?: boolean; // Whether to count total (expensive for large datasets)
  trackPerformance?: boolean; // Record query performance metrics
}

export interface PaginatedResult<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
  hasNext: boolean;
  hasPrevious: boolean;
  queryTime?: number; // ms
  cached?: boolean;
  nextCursor?: string; // For cursor-based pagination
}

/**
 * Enhanced Search/Filter Options
 */
export interface GuardianshipSearchFilters {
  // Ward filters
  wardId?: string;
  wardIds?: string[]; // Bulk lookup
  wardIsMinor?: boolean;
  wardDateOfBirth?: {
    from?: Date;
    to?: Date;
  };
  wardGender?: 'MALE' | 'FEMALE' | 'OTHER';

  // Guardian filters
  guardianId?: string;
  guardianIds?: string[]; // Multiple guardians
  guardianType?: string;
  guardianIsPrimary?: boolean;
  guardianHasActiveConflicts?: boolean;
  guardianComplianceScore?: {
    min?: number;
    max?: number;
  };

  // Status filters
  status?: string | string[]; // Single or multiple statuses
  isEmergency?: boolean;
  isTemporary?: boolean;
  priorityLevel?: 'NORMAL' | 'HIGH' | 'CRITICAL';

  // Date filters
  establishedDate?: {
    from?: Date;
    to?: Date;
  };
  terminationDate?: {
    from?: Date;
    to?: Date;
  };

  // Compliance filters
  complianceStatus?: string | string[];
  hasExpiredBonds?: boolean;
  hasOverdueCompliance?: boolean;
  requiresPropertyManagement?: boolean;
  bondStatus?: string | string[];

  // Risk filters
  riskLevel?: string | string[];
  hasUnresolvedRisks?: boolean;
  riskSeverity?: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

  // Court & Legal filters
  courtOrderExists?: boolean;
  courtStation?: string | string[];
  caseNumber?: string;
  jurisdiction?: 'STATUTORY' | 'ISLAMIC' | 'CUSTOMARY' | 'INTERNATIONAL';

  // Customary Law
  clanName?: string;
  subClan?: string;
  customaryEthnicGroup?: string;

  // Performance filters
  lastActivityDate?: {
    from?: Date;
    to?: Date;
  };
  complianceScore?: {
    min?: number;
    max?: number;
  };

  // Text search
  searchText?: string; // Searches ward name, guardian names, case number
}

/**
 * Enhanced Sort Options with Multiple Fields
 */
export interface GuardianshipSortOptions {
  fields: Array<{
    field:
      | 'establishedDate'
      | 'updatedAt'
      | 'createdAt'
      | 'wardName'
      | 'riskLevel'
      | 'complianceScore'
      | 'priorityLevel';
    direction: 'asc' | 'desc';
  }>;
}

/**
 * Advanced Compliance Filters
 */
export interface ComplianceFilters {
  startDate?: Date;
  endDate?: Date;
  reportType?: string;
  courtStation?: string | string[];
  guardianType?: string;
  isCompliant?: boolean;
  qualityScore?: {
    min?: number;
    max?: number;
  };
  validationStatus?: string | string[];
  autoGenerated?: boolean;
}

/**
 * Enhanced Compliance Statistics
 */
export interface ComplianceStatistics {
  // Basic counts
  totalGuardianships: number;
  totalActive: number;
  totalSuspended: number;
  totalTerminated: number;
  totalEmergency: number;

  // S.72 LSA Bond Compliance
  bondNotRequired: number;
  bondRequiredPending: number;
  bondPosted: number;
  bondForfeited: number;
  bondReleased: number;
  bondComplianceRate: number;

  // S.73 LSA Report Compliance
  reportsTotal: number;
  reportsSubmitted: number;
  reportsAccepted: number;
  reportsOverdue: number;
  reportsRejected: number;
  reportComplianceRate: number;

  // Risk Statistics
  lowRisk: number;
  mediumRisk: number;
  highRisk: number;
  criticalRisk: number;

  // Performance Metrics
  averageComplianceScore: number;
  averageGuardiansPerWard: number;
  averageDaysActive: number;

  // Court Statistics
  statutoryCount: number;
  islamicCount: number;
  customaryCount: number;
  internationalCount: number;

  // Trend Data
  monthlyTrends: Array<{
    month: string;
    created: number;
    terminated: number;
    complianceRate: number;
  }>;
}

/**
 * Enhanced Court Station Statistics
 */
export interface CourtStationStatistics {
  courtStation: string;
  totalGuardianships: number;
  activeGuardianships: number;
  terminatedThisYear: number;
  averageGuardianshipDuration: number; // days
  bondComplianceRate: number;
  reportComplianceRate: number;
  riskDistribution: {
    low: number;
    medium: number;
    high: number;
    critical: number;
  };
  topIssues: Array<{
    issue: string;
    count: number;
  }>;
  performanceMetrics: {
    averageProcessingTime: number; // days
    appealRate: number;
    satisfactionScore: number; // 0-100
  };
}

/**
 * Enhanced Guardianship Summary (Optimized for UI)
 */
export interface GuardianshipSummary {
  id: string;
  wardId: string;
  wardName: string;
  wardAge: number;
  wardDateOfBirth: Date;
  guardiansCount: number;
  primaryGuardian?: {
    name: string;
    id: string;
    contact: string;
  };
  status: string;
  establishedDate: Date;
  daysActive: number;
  lastComplianceCheck?: {
    date: Date;
    status: string;
    score: number;
  };
  nextComplianceDue?: Date;
  riskLevel: string;
  complianceScore: number;
  bondStatus: string;
  priority: 'NORMAL' | 'HIGH' | 'CRITICAL';
  requiresImmediateAction: boolean;
  actionItems: string[];
  quickActions: Array<{
    action: string;
    icon: string;
    route: string;
  }>;
}

/**
 * Enhanced Compliance Report Detail
 */
export interface ComplianceDetail {
  guardianshipId: string;
  wardName: string;
  wardId: string;
  wardAge: number;
  guardianNames: string[];
  primaryGuardian: string;
  establishedDate: Date;
  status: string;
  issues: Array<{
    type: 'BOND' | 'REPORT' | 'RISK' | 'OTHER';
    description: string;
    severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
    dueDate?: Date;
  }>;
  lastActionDate: Date;
  lastActionType: string;
  nextDeadline?: Date;
  nextDeadlineType: string;
  complianceScore: number;
  riskLevel: string;
  recommendations: string[];
  escalationRequired: boolean;
  escalationLevel?: 'GUARDIAN' | 'COURT' | 'SOCIAL_SERVICES';
}

/**
 * Comprehensive Compliance Report
 */
export interface ComplianceReport {
  generatedAt: Date;
  generatedBy: string;
  periodStart: Date;
  periodEnd: Date;
  courtStation?: string;

  // Summary
  totalGuardianships: number;
  compliant: number;
  partiallyCompliant: number;
  nonCompliant: number;
  criticalNonCompliance: number;

  // Detailed Analysis
  complianceByType: Record<string, number>;
  complianceByCourtStation: Record<string, number>;
  complianceByRiskLevel: Record<string, number>;

  // Issues Breakdown
  topIssues: Array<{
    issue: string;
    count: number;
    severity: string;
  }>;

  // Details
  details: ComplianceDetail[];

  // Recommendations
  executiveSummary: string;
  keyFindings: string[];
  recommendedActions: Array<{
    action: string;
    priority: 'HIGH' | 'MEDIUM' | 'LOW';
    responsible: string;
    timeline: string;
  }>;

  // Appendices
  appendices: Array<{
    title: string;
    content: string;
  }>;
}

/**
 * Enhanced E-Filing Data
 */
export interface EfilingData {
  caseNumber: string;
  courtStation: string;
  filingDate: Date;
  filingType: 'INITIAL' | 'AMENDMENT' | 'TERMINATION' | 'COMPLIANCE';
  guardianshipId: string;
  wardName: string;
  wardIdNumber?: string;
  guardianNames: string[];
  guardianIdNumbers: string[];
  documents: EfilingDocument[];
  metadata: {
    filingCategory: string;
    urgencyLevel: string;
    requiresHearing: boolean;
    estimatedDuration: number; // minutes
  };
  payment: {
    required: boolean;
    amount?: number;
    paid?: boolean;
    receiptNumber?: string;
  };
}

export interface EfilingDocument {
  documentType: string;
  documentId: string;
  title: string;
  required: boolean;
  uploaded: boolean;
  uploadDate?: Date;
  verified: boolean;
  verificationMethod?: string;
  size?: number;
  mimeType?: string;
  downloadUrl?: string;
}

/**
 * Audit and Version Control
 */
export interface GuardianshipVersion {
  version: number;
  updatedAt: Date;
  updatedBy?: string;
  eventType: string;
  changes: {
    before: Record<string, any>;
    after: Record<string, any>;
    diff: Array<{
      path: string;
      before: any;
      after: any;
      type: 'ADDED' | 'REMOVED' | 'MODIFIED';
    }>;
  };
  source: 'USER' | 'SYSTEM' | 'COURT' | 'API';
  ipAddress?: string;
  userAgent?: string;
}

export interface VersionComparison {
  version1: number;
  version2: number;
  aggregateId: string;
  comparedAt: Date;
  differences: {
    field: string;
    path: string[];
    before: any;
    after: any;
    significance: 'MINOR' | 'MODERATE' | 'MAJOR' | 'CRITICAL';
    impact: string[];
  }[];
  summary: {
    totalChanges: number;
    criticalChanges: number;
    majorChanges: number;
    moderateChanges: number;
    minorChanges: number;
  };
}

/**
 * Export and Backup Data
 */
export interface GuardianshipExportOptions {
  format: 'JSON' | 'CSV' | 'PDF' | 'EXCEL';
  include: {
    aggregate: boolean;
    guardianAssignments: boolean;
    complianceChecks: boolean;
    events: boolean;
    attachments: boolean;
  };
  dateRange?: {
    from: Date;
    to: Date;
  };
  compress?: boolean;
  passwordProtect?: boolean;
}

export interface GuardianshipExport {
  exportId: string;
  requestedAt: Date;
  requestedBy: string;
  format: string;
  size: number;
  downloadUrl: string;
  expiresAt: Date;
  summary: {
    guardianships: number;
    guardianAssignments: number;
    complianceChecks: number;
    events: number;
  };
}

/**
 * Bulk Operation Results
 */
export interface BulkOperationResult {
  operationId: string;
  startedAt: Date;
  completedAt: Date;
  initiatedBy: string;
  totalItems: number;
  successful: number;
  failed: number;
  failures: Array<{
    id: string;
    error: string;
    details?: any;
  }>;
  summary: string;
  downloadUrl?: string;
}

/**
 * System Health Metrics
 */
export interface RepositoryHealthMetrics {
  database: {
    connectionPool: {
      total: number;
      active: number;
      idle: number;
      waiting: number;
    };
    queryPerformance: {
      averageQueryTime: number;
      slowQueries: number;
      cacheHitRate: number;
    };
  };
  cache: {
    hitRate: number;
    size: number;
    evictions: number;
  };
  performance: {
    averageSaveTime: number;
    averageFindTime: number;
    peakLoad: number;
  };
  alerts: Array<{
    level: 'INFO' | 'WARNING' | 'ERROR';
    message: string;
    timestamp: Date;
  }>;
}

/**
 * 🎯 Guardianship Repository Interface with Event Sourcing Support
 */
export interface IGuardianshipRepository {
  // ============================================================================
  // AGGREGATE PERSISTENCE (CQRS - Command Side)
  // ============================================================================

  /**
   * Save guardianship aggregate with full event sourcing
   *
   * TRANSACTION FLOW:
   * 1. Begin transaction
   * 2. Check optimistic lock version
   * 3. Save aggregate root state (snapshot)
   * 4. Save all child entities (guardian assignments, compliance checks)
   * 5. Save all domain events to event store
   * 6. Update read models (projections)
   * 7. Commit transaction
   * 8. Clear uncommitted events from aggregate
   *
   * PERFORMANCE OPTIMIZATIONS:
   * - Uses batch inserts for child entities
   * - Event compression for large events
   * - Conditional snapshot creation (every 10 events)
   */
  save(guardianship: GuardianshipAggregate): Promise<GuardianshipAggregate>;

  /**
   * Batch save for high-volume operations
   * Uses parallel processing with chunking
   */
  saveMany(guardianships: GuardianshipAggregate[]): Promise<BulkOperationResult>;

  /**
   * Soft delete with legal retention compliance
   * Maintains all data for audit trail
   */
  softDelete(id: string, deletedBy: string, reason: string): Promise<void>;

  /**
   * Restore soft-deleted guardianship
   * Requires audit trail of restoration
   */
  restore(id: string, restoredBy: string): Promise<GuardianshipAggregate>;

  // ============================================================================
  // AGGREGATE QUERIES (CQRS - Query Side)
  // ============================================================================

  /**
   * Find by ID with configurable depth
   * Depth 0: Aggregate only
   * Depth 1: + Guardian assignments
   * Depth 2: + Compliance checks
   * Depth 3: + Events
   */
  findById(id: string, depth?: 0 | 1 | 2 | 3): Promise<GuardianshipAggregate | null>;

  /**
   * Find active guardianship by ward ID
   * Includes emergency and suspended statuses
   */
  findActiveByWardId(wardId: string): Promise<GuardianshipAggregate | null>;

  /**
   * Find all guardianships for ward (including historical)
   * Sorted by established date descending
   */
  findAllByWardId(wardId: string): Promise<GuardianshipAggregate[]>;

  /**
   * Find guardianships where person is guardian
   * Supports multiple roles and statuses
   */
  findByGuardianId(
    guardianId: string,
    options?: {
      activeOnly?: boolean;
      role?: string;
      includeSuspended?: boolean;
    },
  ): Promise<GuardianshipAggregate[]>;

  /**
   * Find by court case with advanced matching
   * Supports partial case number matching
   */
  findByCourtCaseNumber(courtCaseNumber: string): Promise<GuardianshipAggregate[]>;

  /**
   * Advanced search with full-text capabilities
   * Uses database-specific optimizations
   */
  search(
    filters: GuardianshipSearchFilters,
    pagination: PaginationOptions,
    sort?: GuardianshipSortOptions,
  ): Promise<PaginatedResult<GuardianshipAggregate>>;

  /**
   * Count with same filters as search
   * Optimized for performance
   */
  count(filters: GuardianshipSearchFilters): Promise<number>;

  // ============================================================================
  // COMPLIANCE & RISK QUERIES (S.72 & S.73 LSA)
  // ============================================================================

  /**
   * Find guardianships requiring immediate compliance action
   * Prioritized by severity and deadline proximity
   */
  findRequiringComplianceAction(options?: {
    severity?: 'HIGH' | 'MEDIUM' | 'LOW';
    deadlineWithinDays?: number;
    courtStation?: string;
  }): Promise<GuardianshipAggregate[]>;

  /**
   * Find guardianships with bond issues
   * Expanded to include all bond-related problems
   */
  findWithBondIssues(): Promise<GuardianshipAggregate[]>;

  /**
   * Find guardianships with overdue compliance checks
   * Includes grace period calculations
   */
  findWithOverdueCompliance(gracePeriodExpired?: boolean): Promise<GuardianshipAggregate[]>;

  /**
   * Find guardianships with high-risk factors
   * Uses risk scoring algorithm
   */
  findHighRiskGuardianships(threshold?: number): Promise<GuardianshipAggregate[]>;

  /**
   * Find wards approaching majority with auto-dissolution planning
   */
  findWardsApproachingMajority(
    withinDays: number,
    options?: {
      includeAlreadyPlanned?: boolean;
      courtStation?: string;
    },
  ): Promise<GuardianshipAggregate[]>;

  // ============================================================================
  // STATISTICS & ANALYTICS
  // ============================================================================

  /**
   * Comprehensive compliance statistics
   * Cached for performance
   */
  getComplianceStatistics(courtStation?: string): Promise<ComplianceStatistics>;

  /**
   * Court station analytics dashboard
   */
  getCourtStationStatistics(
    courtStation?: string,
  ): Promise<CourtStationStatistics | CourtStationStatistics[]>;

  /**
   * Generate compliance report with configurable detail
   */
  generateComplianceReport(filters: ComplianceFilters): Promise<ComplianceReport>;

  /**
   * Get guardianship summary for UI dashboards
   * Optimized for fast loading
   */
  getGuardianshipSummary(id: string): Promise<GuardianshipSummary>;

  /**
   * Get multiple summaries for list views
   */
  getGuardianshipSummaries(ids: string[]): Promise<GuardianshipSummary[]>;

  // ============================================================================
  // EVENT SOURCING & AUDIT
  // ============================================================================

  /**
   * Rebuild aggregate from event stream at specific point in time
   */
  rebuildFromEvents(id: string, upToDate?: Date): Promise<GuardianshipAggregate | null>;

  /**
   * Get event history with filtering
   */
  getEventHistory(
    id: string,
    options?: {
      eventTypes?: string[];
      fromDate?: Date;
      toDate?: Date;
      limit?: number;
    },
  ): Promise<DomainEvent[]>;

  /**
   * Get version history with detailed diffs
   */
  getVersionHistory(id: string): Promise<GuardianshipVersion[]>;

  /**
   * Compare versions with semantic diff
   */
  compareVersions(id: string, version1: number, version2: number): Promise<VersionComparison>;

  // ============================================================================
  // BULK OPERATIONS & EXPORT
  // ============================================================================

  /**
   * Bulk update with rollback support
   */
  bulkUpdate(
    ids: string[],
    updates: Record<string, any>,
    updatedBy: string,
  ): Promise<BulkOperationResult>;

  /**
   * Export guardianships for backup or transfer
   */
  exportGuardianships(options: GuardianshipExportOptions): Promise<GuardianshipExport>;

  /**
   * Import guardianships from export
   */
  importGuardianships(
    data: any,
    importedBy: string,
    options?: {
      conflictResolution?: 'SKIP' | 'OVERWRITE' | 'MERGE';
      validateOnly?: boolean;
    },
  ): Promise<BulkOperationResult>;

  // ============================================================================
  // SYSTEM MANAGEMENT
  // ============================================================================

  /**
   * Get repository health metrics
   */
  getHealthMetrics(): Promise<RepositoryHealthMetrics>;

  /**
   * Optimize repository performance
   */
  optimize(): Promise<void>;

  /**
   * Clear cache for specific guardianship
   */
  clearCache(id: string): Promise<void>;

  /**
   * Clear all cache
   */
  clearAllCache(): Promise<void>;
}

// ============================================================================
// EXCEPTION HIERARCHY
// ============================================================================

export abstract class RepositoryException extends Error {
  constructor(
    message: string,
    public readonly code: string,
    public readonly context?: Record<string, any>,
    public readonly cause?: Error,
  ) {
    super(message);
    this.name = 'RepositoryException';
  }
}

export class ConcurrencyError extends RepositoryException {
  constructor(aggregateId: string, expectedVersion: number, actualVersion: number) {
    super(
      `Concurrency conflict for aggregate ${aggregateId}. Expected version ${expectedVersion}, got ${actualVersion}`,
      'CONCURRENCY_ERROR',
      { aggregateId, expectedVersion, actualVersion },
    );
    this.name = 'ConcurrencyError';
  }
}

export class GuardianshipNotFoundException extends RepositoryException {
  constructor(id: string) {
    super(`Guardianship with ID ${id} not found`, 'NOT_FOUND', { id });
    this.name = 'GuardianshipNotFoundException';
  }
}

export class OptimisticLockException extends RepositoryException {
  constructor(aggregateId: string, expectedVersion: number, actualVersion: number) {
    super(
      `Optimistic lock failed for ${aggregateId}. Version mismatch: expected ${expectedVersion}, actual ${actualVersion}`,
      'OPTIMISTIC_LOCK_ERROR',
      { aggregateId, expectedVersion, actualVersion },
    );
    this.name = 'OptimisticLockException';
  }
}

export class ValidationException extends RepositoryException {
  constructor(
    message: string,
    public readonly errors: Record<string, string[]>,
  ) {
    super(message, 'VALIDATION_ERROR', { errors });
    this.name = 'ValidationException';
  }
}

export class TransactionException extends RepositoryException {
  constructor(
    message: string,
    public readonly transactionId?: string,
    cause?: Error,
  ) {
    super(message, 'TRANSACTION_ERROR', { transactionId }, cause);
    this.name = 'TransactionException';
  }
}

export class EventStoreException extends RepositoryException {
  constructor(
    message: string,
    public readonly eventId?: string,
    cause?: Error,
  ) {
    super(message, 'EVENT_STORE_ERROR', { eventId }, cause);
    this.name = 'EventStoreException';
  }
}

// ============================================================================
// INJECTION TOKENS (NestJS Dependency Injection)
// ============================================================================

/**
 * Primary repository token for application services
 */
export const GUARDIANSHIP_REPOSITORY = 'GUARDIANSHIP_REPOSITORY';

/**
 * Read-only repository for query operations (CQRS)
 */
export const GUARDIANSHIP_READ_REPOSITORY = 'GUARDIANSHIP_READ_REPOSITORY';

/**
 * Event store for event sourcing
 */
export const GUARDIANSHIP_EVENT_STORE = 'GUARDIANSHIP_EVENT_STORE';

/**
 * Cache manager for performance optimization
 */
export const GUARDIANSHIP_CACHE_MANAGER = 'GUARDIANSHIP_CACHE_MANAGER';

/**
 * Unit of Work for transaction management
 */
export const GUARDIANSHIP_UNIT_OF_WORK = 'GUARDIANSHIP_UNIT_OF_WORK';

// ============================================================================
// UNIT OF WORK INTERFACE (Transaction Management)
// ============================================================================

export interface IUnitOfWork {
  begin(): Promise<void>;
  commit(): Promise<void>;
  rollback(): Promise<void>;
  isActive(): boolean;
  getTransactionId(): string;

  // Repository access within transaction
  getRepository<T>(token: string): T;

  // Event publishing within transaction
  publishEvents(events: DomainEvent[]): Promise<void>;
}

// ============================================================================
// CACHE MANAGER INTERFACE
// ============================================================================

export interface ICacheManager {
  get<T>(key: string): Promise<T | null>;
  set<T>(key: string, value: T, ttl?: number): Promise<void>;
  delete(key: string): Promise<void>;
  clear(): Promise<void>;
  has(key: string): Promise<boolean>;
  keys(pattern?: string): Promise<string[]>;

  // Advanced caching
  getOrSet<T>(key: string, factory: () => Promise<T>, ttl?: number): Promise<T>;
  mGet<T>(keys: string[]): Promise<Array<T | null>>;
  mSet(values: Array<{ key: string; value: any; ttl?: number }>): Promise<void>;

  // Cache statistics
  getStats(): Promise<{
    hits: number;
    misses: number;
    hitRate: number;
    size: number;
    memoryUsage: number;
  }>;
}

// ============================================================================
// EVENT STORE INTERFACE
// ============================================================================

export interface IEventStore {
  // Event persistence
  saveEvents(aggregateId: string, events: DomainEvent[], expectedVersion: number): Promise<void>;

  // Event retrieval
  getEvents(aggregateId: string): Promise<DomainEvent[]>;
  getEventsSince(aggregateId: string, sinceVersion: number): Promise<DomainEvent[]>;
  getEventsByType(
    eventType: string,
    options?: {
      fromDate?: Date;
      toDate?: Date;
      limit?: number;
    },
  ): Promise<DomainEvent[]>;

  // Event subscription
  subscribe(
    handler: (event: DomainEvent) => Promise<void>,
    options?: {
      eventTypes?: string[];
      aggregateTypes?: string[];
    },
  ): Promise<string>; // Returns subscription ID

  unsubscribe(subscriptionId: string): Promise<void>;

  // Event store management
  createSnapshot(aggregateId: string): Promise<void>;
  getLatestSnapshot(aggregateId: string): Promise<any>;
  cleanupOldEvents(retentionDays: number): Promise<number>;

  // Analytics
  getEventStatistics(): Promise<{
    totalEvents: number;
    eventsByType: Record<string, number>;
    eventsByAggregate: Record<string, number>;
    dailyVolume: Array<{ date: string; count: number }>;
  }>;
}
